include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    # Exclude nested package examples - they have their own package context
    # that the root analyzer cannot resolve properly
    - example/**
    - pigeons/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
